### ISSUE TITLE
Getting historical Imagery

### ISSUE THREAD

**Issue by Kunal2341** [Jimut123/jimutmap#12]
When we the base code 
```
download_obj = api(min_lat_deg = 10,
                      max_lat_deg = 10.2,
                      min_lon_deg = 10,
                      max_lon_deg =  base 11,
                      zoom = 19,
                      verbose = False,
                      threads_ = 5, 
                      container_dir = ".")
```
it downloads the current image of that specific location. Is there any possible way we can implement a way to get the historical image of any location (within reason). 

Also is there any way I can only get satillieste images and none of the other formats

**Comment by Jimut123** [comment]
@Kunal2341 It is very unlikely that [https://satellites.pro/](https://satellites.pro/) will store multiple versions of the same image at different time. 
> Also is there any way I can only get satillieste images and none of the other formats

Do you mean only the aerial imagery tile? 
Then yes, you have to use
```
api.download( getMasks:bool= False, latLonResolution:float= 0.0005, **kwargs)
```
with minor changes you can achieve that.

**Comment by tigerhawkvok** [comment]
@Kunal2341 You'll want a provider like Nearmap, Maxar, Planet, or Ecopia for historical imagery. Most of them should have trial accounts for you to experiment.
