### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by aftoryte** [Jimut123/jimutmap#2]
Hello, 
first of all thank you for this library! 
I do have some problems with it, after initializing, the CPU`s are busy and the script is running, but 0%|          | 0/117 [00:00<?, ?it/s] - this is not indicating any work done, after hours. The OS is Windows 10, all pre-requisites are installed as mentioned in README.

Greetings !

**Comment by Jimut123** [comment]
Hi @aftoryte,
Could you also provide the parameters that you were providing in the API,
i.e., 
```
a=api('&api-access-key',min_lat_deg,max_lat_deg,min_lon_deg,max_lon_deg,zoom=19,verbose=False,threads_=110)
```
Note the `&api-access-key` is valid for only 25 mins... and you have to renew the API key..
An example for currently valid API key is `&accessKey=1603792408_6856021874907783602_%2F_E4geXkEerPkVh%2F6wUU%2B2KiLriaVqFQbFt5F%2FiffnXlk%3D`
```
! pip install jimutmap
from jimutmap import api
# 24.785181,85.167236,19
a=api('&accessKey=1603792408_6856021874907783602_%2F_E4geXkEerPkVh%2F6wUU%2B2KiLriaVqFQbFt5F%2FiffnXlk%3D',24.785181,24.9,85.167236,86,zoom=19,verbose=False,threads_=5)
a.download()
```
This works fine in Colab, though it is linux, not tested in Windows.

Kindly provide the parameters to me in reply to this comment along with the name of the place which you were scraping.
https://colab.research.google.com/drive/1mrGeIkYXNg_oUi2BQdk3sV8voJiiaL1t?usp=sharing
This works fine, don't know what might be wrong.

Also, try to minimize the threads, i.e., `threads_=5` or something.

**Comment by aftoryte** [comment]
Here are the parameters :
a = api('&accessKey=1603791984_8942722137763956262_%2F_A8356cWLsxw1EA81FNHGNbh56cVKvN1A1HSr1N2NvIY%3D',
        42.144378,42.086312,24.761338,24.626069,zoom=19,verbose=False,threads_=50)
https://satellites.pro/Bulgaria_map#42.140591,24.756060,14

Greetings !

**Comment by Jimut123** [comment]
> Here are the parameters :
> a = api('&accessKey=1603791984_8942722137763956262_%2F_A8356cWLsxw1EA81FNHGNbh56cVKvN1A1HSr1N2NvIY%3D',
> 42.144378,42.086312,24.761338,24.626069,zoom=19,verbose=False,threads_=50)
> https://satellites.pro/Bulgaria_map#42.140591,24.756060,14
> 
> Greetings !

Ahh, I think `a=api('&accessKey=1603793379_5651500765499839299_%2F_iUmVXkM%2BRJobI7XMCxgIRpBczUdeswNcF1DtNHWaspc%3D',42.086312,42.144378,24.626069,24.761338,zoom=19,verbose=False,threads_=5)` this will work, you are supposed to give the min lat degree then the max lat deg, and the min lon deg then the max lon deg.

I will be making some changes to the code, since this is not robust to that thing. But try doing that, it might work..

**Comment by aftoryte** [comment]
> > Here are the parameters :
> > a = api('&accessKey=1603791984_8942722137763956262_%2F_A8356cWLsxw1EA81FNHGNbh56cVKvN1A1HSr1N2NvIY%3D',
> > 42.144378,42.086312,24.761338,24.626069,zoom=19,verbose=False,threads_=50)
> > https://satellites.pro/Bulgaria_map#42.140591,24.756060,14
> > Greetings !
> 
> Ahh, I think `a=api('&accessKey=1603793379_5651500765499839299_%2F_iUmVXkM%2BRJobI7XMCxgIRpBczUdeswNcF1DtNHWaspc%3D',42.086312,42.144378,24.626069,24.761338,zoom=19,verbose=False,threads_=5)` this will work, you are supposed to give the min lat degree then the max lat deg, and the min lon deg then the max lon deg.
> 
> I will be making some changes to the code, since this is not robust to that thing. But try doing that, it might work..

Don`t think that is the problem:
https://colab.research.google.com/drive/1eB4Yc-rCya5cVEuwpU6fzlzESzU4uyzS#scrollTo=UyLJAwQTbV2w
Maybe there is something about mine PC is not allowing, or some kind of certificate ?

**Comment by Jimut123** [comment]
Not sure, but this works for Linux at the moment not sure about Windows. Will look into the matter soon. You may try to use Colab and then zip it and download it in your local machine at the moment, if it is urgent. 

I have to look this issue for windows.

**Comment by Jimut123** [comment]
Also try doing,
```
pip uninstall jimutmap
pip install jimutmap
```
Yup, it happened to be an unknown bug probably. 
```
from jimutmap import api
# 24.785181,85.167236,19
a=api('&accessKey=1603794865_4010858648804025441_%2F_NIsGg8FFC2SywBMOIcV0U8ej%2FWfm71CexL5qTE4hdH0%3D',42.086312,42.144378,24.626069,24.761338,zoom=19,verbose=False,threads_=5)
# 42.144378,42.086312,24.761338,24.626069
a.download()
```

And tell me if it works or not.

Best,
-Jimut

**Comment by aftoryte** [comment]
> Also try doing this @aftoryte ,
> 
> ```
> pip uninstall jimutmap
> pip install jimutmap
> ```
> 
> Yup, it happened to be an unknown bug probably.
> 
> ```
> from jimutmap import api
> # 24.785181,85.167236,19
> a=api('&accessKey=1603794865_4010858648804025441_%2F_NIsGg8FFC2SywBMOIcV0U8ej%2FWfm71CexL5qTE4hdH0%3D',42.086312,42.144378,24.626069,24.761338,zoom=19,verbose=False,threads_=5)
> # 42.144378,42.086312,24.761338,24.626069
> a.download()
> ```
> 
> And tell me if it works or not.
> 
> for me it works...
> Check this...
> 
> ![Screenshot from 2020-10-27 15-38-21](https://user-images.githubusercontent.com/25353228/97287466-9f1cd900-186a-11eb-88a7-867d456fb739.png)
> 
> Best,
> -Jimut

Yes it`s working in your notebook, any other notebook cause the same problem or an IDE. Don`t know what is the problem. Thanks anyway!

**Comment by Jimut123** [comment]
Probably Unknown Windows Problem.
Cheerio!

**Comment by Jimut123** [comment]
@aftoryte There has been several improvements last few months. Check if the bug still persists... or not...
