### ISSUE TITLE
Black tiles and Extremely slow download speed 

### ISSUE THREAD

**Issue by Gr1ff1th123** [Jimut123/jimutmap#26]
The script downloads nothing but black tiles at a rate of 0.0017232894897460938 MiB/s

**To Reproduce**
Run either Test.Py or a modified version of it

**Desktop 
 - OS: [Win 10]
 - Browser [Chrome]
 - Python 3.7
 - Jimutmap 1.4.2
 
**Additional context**
Zoom level was 17, Cores 4, Satellites Pro had up to 19 zoom for the region being downloaded, API key auto generated
**Screenshots**
![issue1](https://github.com/Jimut123/jimutmap/assets/138775888/7cd138bb-e2cb-48d4-bbc6-030deebc2c34)
![Issue2](https://github.com/Jimut123/jimutmap/assets/138775888/22474679-1480-4fe6-83e2-bc503956b0fa)

**Program**
[modifiedtest.txt](https://github.com/Jimut123/jimutmap/files/11967270/modifiedtest.txt)

**Comment by Jimut123** [comment]
Hi, this is a common issue rn; I have to look into this. If you find any solution, don't hesitate to do a PR.

**Comment by Gr1ff1th123** [comment]
Thank you for looking into it and making the program, I'll update the issue if I can find anyway to solve it, I'm going to attempt to download different regions, sizes and zoom levels, however sats.pro went up to zoom level 19 and I was trying to download zoom level 17, additionally do you have any idea what's causing the extremely slow download?

**Comment by Jimut123** [comment]
Internet connection might be one thing; the other thing might be the bandwidth of satellites.pro in your region. I am not sure about any other reason that might cause the problem of slow download, you can try in google colab platform, and if it is slow there, then it means that the satellites.pro's bandwidth is slow around your area. There might be different servers that are providing different speeds in different regions of the world.
