### ISSUE TITLE
Does it still work?

### ISSUE THREAD

**Issue by manupillai308** [Jimut123/jimutmap#28]
I came here from a research project requiring satellite images. I noticed somethings that are not mentioned in the project.
First, getting the API access key, as soon as open the developer tools for the network tab, the GET request for tiles starts getting rejected from the server.

If I try doing it from the selenium headless driver, it gets timeout. Did the satellite.pro team patched the scraping vulnerability or is it just a random chance that this is happening?

**Comment by Jimut123** [comment]
I have got some time today to check the code, looks like it is not working anymore. Maybe there is some hack to bypass the current issue, but someone needs to check. I'm not sure if this will work in the future, since chromedriver is working, just .get is not working...
