### ISSUE TITLE
Improvement on _getAPIKey method

### ISSUE THREAD

**Issue by saulosouzahere** [Jimut123/jimutmap#9]
Some internet connections -such as mine- are slower than others. In my case the attribute `'data-map-printing-background' ` wasn't loading fast enough so the value of `mapData` was None and an error was raised. 
Code:
```
time.sleep(15)
baseMap = driver.find_element_by_css_selector("#map-canvas .leaflet-mapkit-mutant")
mapData = baseMap.get_attribute("data-map-printing-background")
```

The wait time(5 seconds) is not flexible enough for all internet connections, for me a 10-15 seconds wait works best. Maybe it would be better to build a version of the code that is not type-dependent but situation-dependent.

I will create a fork if i find the time.

**Comment by Jimut123** [comment]
That will be awesome!

**Comment by tigerhawkvok** [comment]
My bad @saulosouzahere ! I wrote that for my own use case and I sit on a 300Mbps connection 🤦‍♂️ 

I'm still playing with satellite data, and will contribute more updates here (including a tile stitcher) when I'm done with this in a few weeks. Until then, I don't have a clean version to merge back.

Here's a version of the API key fetch that keeps retrying until `timeout`  seconds:


```python
    def _getAPIKey(self, timeout:float= 60) -> str:
        """
        Use a headless Chrome/Chromium instance to scrape the access key
        from the data-map-printing-background attribute of Apple Maps.
        """
        SAMPLE_KEY = r"1614125879_3642792122889215637_%2F_RwvhYZM5fKknqTdkXih2Wcu3s2f3Xea126uoIuDzUIY%3D"
        KEY_START = r"&accessKey="
        chromeDriverPath = chromedriver_autoinstaller.install(cwd= True)
        options = webdriver.ChromeOptions()
        options.add_argument('headless')
        driver = webdriver.Chrome(executable_path= chromeDriverPath, options=options)
        driver.get("https://satellites.pro/USA_map#37.405074,-94.284668,5")
        keyContents = None
        loopStartTime = dt.datetime.now()
        while keyContents is None and (dt.datetime.now() - loopStartTime).total_seconds() < timeout:
            time.sleep(2.5)
            try:
                baseMap = driver.find_element_by_css_selector("#map-canvas .leaflet-mapkit-mutant")
                mapData = baseMap.get_attribute("data-map-printing-background")
                accessKeyStart = mapData.find(KEY_START)
                accessKeyEnd = accessKeyStart + int(1.5 * len(SAMPLE_KEY))
                searchForKey = mapData[accessKeyStart:accessKeyEnd]
                keyContents = searchForKey[len(KEY_START):]
                keyEnd = keyContents.find("&")
                keyContents = keyContents[:keyEnd]
            except Exception: #pylint: disable= broad-except
                keyContents = None
        if keyContents is None:
            raise TimeoutError(f"Unable to automatically fetch API key in {timeout}s")
        self.ac_key = keyContents
        return keyContents
```

I've also attached my **very not ready and not productionalized** code to unify map fetching from several providers, which also includes some code to automatically tile the apple maps images into a larger image that @Jimut123 can probably standalone fold into this project long before I get to it :-)

[MapFetcher.zip](https://github.com/Jimut123/jimutmap/files/6320085/MapFetcher.zip)

( @Jimut123  -- see `ImageDeTiler.py` and the new kwarg `byDir` in the `download` method in `jimutmap` )

**Comment by Jimut123** [comment]
@tigerhawkvok, lol, at this point of time, I have become too lazy to contribute in this project (due to thesis work and other paper stuffs). I would be more than happy if you do the complicated stuffs, testing and then add the PR ;)

I am assigning you to this issue, take your time, since it will take some time to do my unfinished stuffs.
